language: ruby
rvm:
  - 2.3.1
sudo: required
dist: trusty
cache:
  bundler: true
before_install:
  - gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: never
